Repository kosa3-OverClock/MoveToMove_MOM_FE, pull requests merged in 2024-09, with the labels that each got.

#2 Feat: 사이드바 기능 구현 및 api 인스턴스 구현
  public/index.html
  src/api/axiosInstance.js
  src/assets/move-to-move-logo2.png
  src/components/layout/MainLayout.vue
  src/stores/navigationStore.js
Labels: enhancement

#5 Feat/bjw/signon#3 회원가입 기능 구현
  package-lock.json
  src/components/layout/AuthLayout.vue
Labels: enhancement

#6 Feat: 공통 버튼 item 컴포넌트 추가
  src/components/common/item/RoundButtonItem.vue
  src/components/layout/MainLayout.vue
  src/main.js
Labels: enhancement

#10 Change/bjw/alert창 css 수정
  src/components/common/item/ErrorAlertItem.vue
  src/components/common/item/RoundButtonItem.vue
  src/components/layout/AuthLayout.vue
Labels: modify

#14 Feat: 회원탈퇴 UI 생성
  src/components/common/AlertMessage.vue
  src/components/view/WithdrawCompo.vue
  src/router/router.js
Labels: enhancement

#13 Modify: 로그아웃 디자인 수정
  src/components/layout/MainLayout.vue
Labels: modify

#15 Modify: axios 경로 수정
  src/components/layout/MainLayout.vue
Labels: modify

#16 Feat/bjw/signon Pinia 상태 코드로 수정
  package-lock.json
  package.json
  src/api/axiosInstance.js
  src/components/common/SocialLoginCallback.vue
  src/components/common/item/ErrorAlertItem.vue
  src/components/layout/AuthLayout.vue
  src/main.js
  src/plugins/interceptors.js
  src/stores/memberStore.js
Labels: enhancement, modify

#17 Modify: alertCheckMessage 수정
  src/components/common/AlertCheckMessage.vue
  src/components/common/AlertMessage.vue
  src/components/view/WithdrawCompo.vue
Labels: enhancement, modify

#20 Modify: 회원탈퇴 기능 수정
  package-lock.json
  package.json
  src/components/common/AlertCheckMessage.vue
  src/components/common/ConfirmAlertCompo.vue
  src/components/view/WithdrawCompo.vue
Labels: modify

#21 Modify: 폴더 구조와 유저 정보 데이터 바인딩 수정
  src/assets/folders24.svg
  src/components/common/item/RoundButtonItem.vue
  src/components/layout/MainLayout.vue
  src/components/view/KanbanBoardCompo.vue
  src/main.js
  src/stores/memberStore.js
Labels: modify

#25 Feat/bjw/kanban card 칸반카드 오픈
  src/components/common/CardCommentForm.vue
  src/components/common/CardContent.vue
  src/components/common/CardHeader.vue
  src/components/layout/KanbanCardLayout.vue
  src/components/view/CardOpenCompo.vue
  src/components/view/KanbanCardCompo.vue
  src/components/view/KanbanColumnCompo.vue
Labels: enhancement

#26 modify: 토큰관련 수정
  src/api/axiosInstance.js
  src/components/layout/AuthLayout.vue
  src/components/layout/MainLayout.vue
  src/plugins/interceptors.js
  src/stores/memberStore.js
Labels: modify

#27 Modify: 비밀번호 변경 모달 ui 수정
  src/components/common/PasswordModal.vue
  src/components/common/PasswordRecoveryDialog.vue
  src/components/layout/AuthLayout.vue
Labels: modify

#28 Feat: 1차적 main merge
  .env
  .eslintrc.js
  package-lock.json
  package.json
  public/index.html
  src/App.vue
  src/api/axiosInstance.js
  src/assets/basic-profile.png
  src/assets/folders24.svg
  src/assets/kakao_login_large_wide.png
  src/assets/move-to-move-logo2.png
  src/assets/web_light_rd_na@4x.png
  src/components/ChatTestCompo.vue
  src/components/HelloWorld.vue
  src/components/common/AlarmMessage.vue
  src/components/common/AlarmModal.vue
  src/components/common/AlertCheckMessage.vue
  src/components/common/AlertDialog.vue
  src/components/common/CardCommentForm.vue
  src/components/common/CardComments.vue
  src/components/common/CardContent.vue
  src/components/common/CardContentLeft.vue
  src/components/common/CardContentRight.vue
  src/components/common/CardHeader.vue
  src/components/common/ConfirmAlertCompo.vue
  src/components/common/KebabMenu.vue
  src/components/common/LogoutConfirmCompo.vue
  src/components/common/PasswordModal.vue
  src/components/common/PasswordRecoveryDialog.vue
  src/components/common/SignupCompleteCompo.vue
  src/components/common/SocialLoginCallback.vue
  src/components/common/item/ErrorAlertItem.vue
  src/components/common/item/ProfileImageItem.vue
  src/components/common/item/RoundButtonItem.vue
  src/components/layout/AuthLayout.vue
  src/components/layout/KanbanCardLayout.vue
  src/components/layout/MainLayout.vue
  src/components/page/PageNotFound.vue
  src/components/view/CardOpenCompo.vue
  src/components/view/ChatCompo.vue
  src/components/view/KanbanBoardCompo.vue
  src/components/view/KanbanCardCompo.vue
  src/components/view/KanbanColumnCompo.vue
  src/components/view/MyPageCompo.vue
  src/components/view/NewProjectCompo.vue
  src/components/view/ProfileCompo.vue
  src/components/view/WithdrawCompo.vue
  src/main.js
  src/router/index.js
  src/router/router.js
  src/stores/index.js
  src/stores/memberStore.js
  src/stores/navigationStore.js
  src/stores/webSocketStore.js
  vue.config.js
Labels: enhancement, modify

#29 Modify: 칸반 컬럼, 카드 UI 수정
  src/components/view/KanbanBoardCompo.vue
  src/components/view/KanbanColumnCompo.vue
Labels: modify

#30 Modify: 마이페이지 수정
  package-lock.json
  package.json
  src/components/layout/MainLayout.vue
  src/components/view/MyPageCompo.vue
  src/main.js
Labels: modify

#31 Modify: 차트 크기 수정
  src/components/view/MyPageCompo.vue
Labels: modify

#34 Feat: 케밥 메뉴 추가, 확인/취소 모달 추가
  src/components/common/AlertOkCancel.vue
  src/components/common/KebabMenu.vue
  src/components/common/KebabProjectMenu.vue
  src/components/view/KanbanBoardCompo.vue
Labels: modify

#37 Modify: 메뉴 구분자 수정
  src/components/common/CardHeader.vue
  src/components/view/KanbanColumnCompo.vue
Labels: modify

#40 Feat: 프로젝트 관리 UI 추가
  src/components/common/KebabProjectMenu.vue
  src/components/view/ManageProjectCompo.vue
  src/router/router.js
Labels: enhancement

#41 Feat: 폴더 생성 기능 구현
  src/components/view/KanbanBoardCompo.vue
Labels: enhancement

#52 Modify: 칸반 카드 열람 수정
  src/components/common/CardCommentForm.vue
  src/components/common/CardComments.vue
  src/components/view/KanbanCardOpenCompo.vue
  src/components/view/KanbanColumnCompo.vue
  src/router/router.js
Labels: modify

#54 Feat: 프로젝트 클릭 기능 구현
  src/App.vue
  src/components/common/item/ProfileImageItem.vue
  src/components/layout/MainLayout.vue
  src/components/view/KanbanBoardCompo.vue
  src/components/view/KanbanCardOpenCompo.vue
  src/components/view/KanbanColumnCompo.vue
  src/stores/kanbanCardStore.js
  src/stores/kanbanColumnStore.js
Labels: enhancement

#65 Modify: 칸반 카드 피니아 수정
  src/components/view/KanbanCardOpenCompo.vue
  src/stores/kanbanCardStore.js
Labels: modify

#72 Modify: 칸반카드 오픈 수정 로직 추가
  src/components/common/item/CardCommonModal.vue
  src/components/view/KanbanCardOpenCompo.vue
  src/stores/kanbanCardStore.js
Labels: modify

#82 Modify: 코멘트 기능 추가
  src/components/common/AlertOkCancel.vue
  src/components/common/CardCommentForm.vue
  src/components/common/CardComments.vue
  src/components/view/KanbanCardOpenCompo.vue
  src/components/view/KanbanColumnCompo.vue
  src/stores/commentStore.js
Labels: modify

#90 Feat: 마이페이지 Task 기능추가
  src/components/view/MyPageCompo.vue
Labels: enhancement

#116 Modify: 칸반카드 정보 수정시 웹소켓 연동
  src/components/view/KanbanCardOpenCompo.vue
  src/components/view/KanbanColumnCompo.vue
  src/stores/webSocketStore.js
Labels: modify
